### ISSUE TITLE
Review. Task#1

### ISSUE THREAD

**Issue by e-kuzminov-md** [vchkhr/mobidev-rubyInternship-bpa#8]
NB! Good separation on PRs, branches. Good Readme docs!

**BASIC PART**
1. DB diagram: Zones table missing, it's better to use a separate table and reuse Zone types for offices
2. Using enums in database is an interesting but not always flexible solution
    @con.exec("CREATE TYPE \"fixture_type\" AS ENUM (
          'Standing desk',
          'Door',
          'Window',
          'Wall poster',
          'Table',
          'ATM Wall',
          'Flag'
        );")
It is not flexible, because each time new Type of Fixture is introduced in csv file you will have to Alter this ENUM.
More often developers just create a separate table fixture_type to hold all possible types of fixture and being able to change them at any time.
3. Make a separate script to call migrations (create / destroy)
4. Classes / objects design is "clever" (good that you have practiced Mixins/included), but it is too implicit and not clear:

a) The whole app is done by calling `DB = Db.new(dbname, user, password)`
you just create an object and it open Pandora Box :)  good design would be to have a separate method call to start business logic.

it's better to call Class `App` or something, not Db. And call like `App.new(...).generate(...)`
so object instantiating and performing heavy jobs - are separated. Do not put a lot of business login in Initializer of the class.

~b) you should have separate scripts to generate each type of reports, or one script, but being able to send parameters there to specify what report you want to have right now~

c) Using a lot of `inludes` not needed here  and in other classes
```
module Parse
  include ParseOffices
  include ParseRooms
  include ParseFixtures
  include ParseMaterials
```
all methods there belong to one logical unit, simply put in into once class, the LoC size of the class is not such a big deal, but it would be better readable in this case.

5. Reports templates without ERB is not perfect. Template HTML is actually not readable, it is very hard to understand and fix.
6. For all reports - grouping should be done with SQL, not in Ruby loops. It will consume too much resources with bigger dataset.

**ADVANCED PART**
Looks fine

**Comment by vchkhr** [comment]
@e-kuzminov-md 
Thanks for your review.
Please check my fixes in the `review` branch in the `challenge-7/advanced` directory.

1. I agree that using a table for Zones would be the best option, but I used Enum(s) for the purpose of learning how it works. Therefore, the table is not shown in the diagram.
2. Discussed during the meeting, we will not fix this one.
3. This applies to the basic part only, which we decided to skip for all students, yes? Create and destroy functionalities are presented in the advanced part using the WEB UI.
4. I merged the files for parsing, but still decided not to do this for reports, since I think that they are too different and navigation through one file is more difficult than through several. If this is still unacceptable in this case where I left the file splitting, let me know. Everything else is fixed, I restructured the project.
5. Fixed, now I send the hash to the view which then parses it.
6. Fixed, now grouping different entities of reports using SQL.

**Comment by e-kuzminov-md** [comment]
> This applies to the basic part only, which we decided to skip for all students, yes? Create and destroy functionalities are presented in the advanced part using the WEB UI.

Ok, I see

> I merged the files for parsing, but still decided not to do this for reports, since I think that they are too different and navigation through one file is more difficult than through several. If this is still unacceptable in this case where I left the file splitting, let me know. Everything else is fixed, I restructured the project.

Yes, I was saying exactly about Parsing methods

> Fixed, now I send the hash to the view which then parses it.

Yes, that looks much better and clean now

> Fixed, now grouping different entities of reports using SQL.

**This is the only one thing I am asking you to fix additionally** 
Grouping via SQL is better. But current implementation is not optimal and looks like you still do not use JOINs correctly

currently most reports has such SQL structure
```sql
SELECT a... FROM (
   SELECT b... FROM ( 
      SELECT c FROM (
.... ODER BY ...
      ) as C JOIN x ON c...
 ) as B JOIN y ON b...
) as A JOIN z ON a....
```
you don't need such complicated and nested structure
multiple JOIN can  be done in a "flat" way, like

```sql
SELECT a.., b..., c... FROM c 
JOIN x ON c...
JOIN y ON b...
JOIN z ON a...
ORDER BY ...
```

**Comment by vchkhr** [comment]
Everything was fixed, I close the issue and merge branches.
